// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0jM6vGprLY6PZeVaux2fk6TcWm8Q5XyQ',
    appId: '1:372066118258:web:8f60d7176e2a295000f0eb',
    messagingSenderId: '372066118258',
    projectId: 'batting-app-ce894',
    authDomain: 'batting-app-ce894.firebaseapp.com',
    storageBucket: 'batting-app-ce894.firebasestorage.app',
    measurementId: 'G-6QMQRLCK6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiRyK44kUwgbLftq3h9Mpk_3zSMTIO2Ow',
    appId: '1:372066118258:android:e22abfd06470578000f0eb',
    messagingSenderId: '372066118258',
    projectId: 'batting-app-ce894',
    storageBucket: 'batting-app-ce894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMvl_XBVr18vcVl8Ukh21GpkqOSuSa-I',
    appId: '1:372066118258:ios:8022ef30fad679e300f0eb',
    messagingSenderId: '372066118258',
    projectId: 'batting-app-ce894',
    storageBucket: 'batting-app-ce894.firebasestorage.app',
    iosBundleId: 'com.example.battingApp',
  );

}